language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev
env:
  - HTTPD_VERSION=httpd-2.2.27 
    APR=apr-1.5.1 
    APR_UTIL=apr-util-1.5.3 
    HTTPD_CONFIG_OPT='--enable-module=all --enable-mods-shared=all --enable-proxy --enable-proxy-http'
  - HTTPD_VERSION=httpd-2.4.9 
    APR=apr-1.5.1 
    APR_UTIL=apr-util-1.5.3 
    HTTPD_CONFIG_OPT=
before_script:
  - echo "HTTPD_VERSION=${HTTPD_VERSION}" > httpd_version
  - echo "APR=${APR}" >> httpd_version
  - echo "APR_UTIL=${APR_UTIL}" >> httpd_version
  - echo "HTTPD_CONFIG_OPT=${HTTPD_CONFIG_OPT}" >> httpd_version
script:
  - sh test.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "BYpv6AjLGEtNMX67AaUEbirIQRX9Tl6ovPA/2+BDdHiNEMr1+xZVhp1rOBEP7nli1opvKe7OfJFNaJ2HRMmECmh3ZtfIiGQ8t3LtKd2kl+6tL9rdYuWo7M9PjGKsVXhcsJlK3FpeYXGGqmxRelapMAs+yn3EWz9S54Yy7QWqO/Q="

